// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppConfig = { autoStart: boolean, uploadDir: string, port: number, passwordEnabled: boolean, password: string, httpsEnabled: boolean, bindIpv6: boolean, 
/**
 * 磁盘最小保留空间（MB）：上传前若磁盘剩余空间低于 (size + disk_min_free_mb*1MB) 即拒绝。
 * 0 表示不启用软限制。默认 500MB，避免写满硬盘把系统搞挂。
 */
diskMinFreeMb: number, };
