// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 审计日志单条记录（P3-18）
 */
export type AuditLog = { id: bigint, ts: bigint, kind: string, ip: string, detail: string, };
