// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileItem = { id: string, name: string, size: number, mime: string, uploaderIp: string, createdAt: bigint, };
